######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 7 17:29:47 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              . \
              setPlayGUI \
              setPlayGUI/outProgramsClasses \
              setPlayGUI/portingClasses \
              setPlayGUI/rcsslog/qt4 \
              setPlayGUI/rcsslog/rcsslogplayer
INCLUDEPATH += . \
               setPlayGUI \
               setPlayGUI/outProgramsClasses \
               setPlayGUI/portingClasses \
               setPlayGUI/rcsslog/qt4 \
               setPlayGUI/rcsslog/rcsslogplayer

# Input
HEADERS += config.h \
           mainwindow.h \
           setPlayGUI/spaction.h \
           setPlayGUI/spdefinitions.h \
           setPlayGUI/spfield.h \
           setPlayGUI/spgraph.h \
           setPlayGUI/spinitdialog.h \
           setPlayGUI/spoutprogram.h \
           setPlayGUI/spplayer.h \
           setPlayGUI/spplayereditordialog.h \
           setPlayGUI/sppoint.h \
           setPlayGUI/spporting.h \
           setPlayGUI/spsetplay.h \
           setPlayGUI/spshowgame.h \
           setPlayGUI/spstep.h \
           setPlayGUI/sptransition.h \
           setPlayGUI/outProgramsClasses/spdebugfcpdebuglogplayer.h \
           setPlayGUI/outProgramsClasses/spdebugfcpdebuglogplayerconfigdialog.h \
           setPlayGUI/outProgramsClasses/sptestrcsoccersim.h \
           setPlayGUI/outProgramsClasses/sptestrcsoccersimconfigdialog.h \
           setPlayGUI/portingClasses/spfcportugalporting.h \
           setPlayGUI/rcsslog/qt4/angle_deg.h \
           setPlayGUI/rcsslog/qt4/ball_painter.h \
           setPlayGUI/rcsslog/qt4/circle_2d.h \
           setPlayGUI/rcsslog/qt4/disp_holder.h \
           setPlayGUI/rcsslog/qt4/field_canvas.h \
           setPlayGUI/rcsslog/qt4/line_2d.h \
           setPlayGUI/rcsslog/qt4/log_player.h \
           setPlayGUI/rcsslog/qt4/log_player_tool_bar.h \
           setPlayGUI/rcsslog/qt4/log_slider_tool_bar.h \
           setPlayGUI/rcsslog/qt4/main_data.h \
           setPlayGUI/rcsslog/qt4/mouse_state.h \
           setPlayGUI/rcsslog/qt4/options.h \
           setPlayGUI/rcsslog/qt4/painter_interface.h \
           setPlayGUI/rcsslog/qt4/player_painter.h \
           setPlayGUI/rcsslog/qt4/vector_2d.h \
           setPlayGUI/rcsslog/rcsslogplayer/gzfstream.h \
           setPlayGUI/rcsslog/rcsslogplayer/handler.h \
           setPlayGUI/rcsslog/rcsslogplayer/parser.h \
           setPlayGUI/rcsslog/rcsslogplayer/types.h \
           setPlayGUI/rcsslog/rcsslogplayer/util.h \
           setPlayGUI/rcsslog/icons/play.xpm \
           setPlayGUI/rcsslog/icons/rev.xpm \
           setPlayGUI/rcsslog/icons/plus.xpm \
           setPlayGUI/rcsslog/icons/minus.xpm \
           setPlayGUI/rcsslog/icons/ff.xpm \
           setPlayGUI/rcsslog/icons/rew.xpm \
           setPlayGUI/rcsslog/icons/next_score.xpm \
           setPlayGUI/rcsslog/icons/prev_score.xpm \
           setPlayGUI/rcsslog/icons/stop.xpm
FORMS += mainwindow.ui \
         setPlayGUI/spinitdialog.ui \
         setPlayGUI/spplayereditordialog.ui \
         setPlayGUI/sprelativepositiondialog.ui \
         setPlayGUI/spsetplay.ui \
         setPlayGUI/outProgramsClasses/spdebugfcpdebuglogplayerconfigdialog.ui \
         setPlayGUI/outProgramsClasses/sptestrcsoccersimconfigdialog.ui
SOURCES += main.cpp \
           mainwindow.cpp \
           setPlayGUI/spaction.cpp \
           setPlayGUI/spfield.cpp \
           setPlayGUI/spgraph.cpp \
           setPlayGUI/spinitdialog.cpp \
           setPlayGUI/spoutprogram.cpp \
           setPlayGUI/spplayer.cpp \
           setPlayGUI/spplayereditordialog.cpp \
           setPlayGUI/sppoint.cpp \
           setPlayGUI/spporting.cpp \
           setPlayGUI/sprelativepositiondialog.cpp \
           setPlayGUI/spsetplay.cpp \
           setPlayGUI/spshowgame.cpp \
           setPlayGUI/spstep.cpp \
           setPlayGUI/sptransition.cpp \
           setPlayGUI/outProgramsClasses/spdebugfcpdebuglogplayer.cpp \
           setPlayGUI/outProgramsClasses/spdebugfcpdebuglogplayerconfigdialog.cpp \
           setPlayGUI/outProgramsClasses/sptestrcsoccersim.cpp \
           setPlayGUI/outProgramsClasses/sptestrcsoccersimconfigdialog.cpp \
           setPlayGUI/portingClasses/spfcportugalporting.cpp \
           setPlayGUI/rcsslog/qt4/angle_deg.cpp \
           setPlayGUI/rcsslog/qt4/ball_painter.cpp \
           setPlayGUI/rcsslog/qt4/circle_2d.cpp \
           setPlayGUI/rcsslog/qt4/disp_holder.cpp \
           setPlayGUI/rcsslog/qt4/field_canvas.cpp \
           setPlayGUI/rcsslog/qt4/line_2d.cpp \
           setPlayGUI/rcsslog/qt4/log_player.cpp \
           setPlayGUI/rcsslog/qt4/log_player_tool_bar.cpp \
           setPlayGUI/rcsslog/qt4/log_slider_tool_bar.cpp \
           setPlayGUI/rcsslog/qt4/main_data.cpp \
           setPlayGUI/rcsslog/qt4/options.cpp \
           setPlayGUI/rcsslog/qt4/player_painter.cpp \
           setPlayGUI/rcsslog/qt4/vector_2d.cpp \
           setPlayGUI/rcsslog/rcsslogplayer/gzfstream.cpp \
           setPlayGUI/rcsslog/rcsslogplayer/parser.cpp \
           setPlayGUI/rcsslog/rcsslogplayer/types.cpp \
           setPlayGUI/rcsslog/rcsslogplayer/util.cpp
RESOURCES += images.qrc
